# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c739f7e2decb54d703e588fd68a242430d0a591e9693e5970294653603bb6f43a65dd78b03487646845f8e68c1029a6c19f2dd4e97c5642ea9a1949e9d0a2e6c

test:
  secret_key_base: 12d8cabd3a5d17a0e395ec4284942c0d8dc4c4d69b73190b5c1b6095d0b7c90290e59496aa06991f6f794e8e7e80f5da6886339eb1d41a64525cf2dd67bd572f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
